#!/usr/bin/env python3
# coding: utf-8
# Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
model_name: "pangu_7B"
model_path: "/path/to/openPangu-Embedded-7B"      # override with --model-path or edit here
exe_mode: "eager"                                  # ["ge_graph", "eager", "acl_graph"]
world_size: 1

model_config:
  mm_quant_mode: A16W16                            # ["A16W16", "A8W8"]
  gmm_quant_mode: A16W16                           # ["A16W16", "A8W8"]
  enable_weight_nz: False
  enable_profiler: False
  with_ckpt: True
  enable_cache_compile: False
  enable_online_split_weight: True
  perfect_eplb: False
  tokenizer_mode: "default"                        # ["default", "chat"]

data_config:
  dataset: "default"                               # ["default", "LongBench"]
  input_max_len: 1536
  max_new_tokens: 32
  batch_size: 1

parallel_config:
  attn_tp_size: 1
  moe_tp_size: 1
  embed_tp_size: 1
  lmhead_tp_size: 1
