#!/usr/bin/env python3
# coding: utf-8
# Copyright (c) Huawei Technologies Co., Ltd. 2024-2026. All rights reserved.
# -----------------------------------------------------------------------------
# snapshot_generator.py
#
# Reads a validated snapshot manifest and produces three artifacts under
# custom/<op>/_debug/:
#
#   1. <op>_<module>_snapshot.py       — copy of the module kernel with
#                                        inspection_<name> buffers assembled
#                                        at each intermediate's probe point.
#   2. <op>_golden_modular_snapshot.py — copy of the modular golden with
#                                        module_<k>_inspect() extended to
#                                        return per-iteration intermediates.
#   3. run_snapshot_bisect.sh          — one-command runner that invokes
#                                        snapshot_bisect.py for the requested
#                                        PyPTO modes (sim/npu) and compares
#                                        them with the torch golden.
#
# Design principle: the generator does NOT do full AST rewriting. Instead it
# relies on MARKER COMMENTS the kernel author leaves in the module file.
# Markers are:
#
#   # <<< SNAPSHOT:before_nt_loop
#   # >>> SNAPSHOT:before_nt_loop
#   # <<< SNAPSHOT:inside_nt_loop
#   # >>> SNAPSHOT:inside_nt_loop
#   # <<< SNAPSHOT:after_nt_loop
#   # >>> SNAPSHOT:after_nt_loop
#
# For each intermediate in the manifest, the generator inserts a small
# pypto.assemble block just before the corresponding closing marker. This
# keeps the generator simple, deterministic, and diff-friendly.
#
# The golden side uses the same marker convention in the modular golden.
# -----------------------------------------------------------------------------

from __future__ import annotations

import argparse
import logging
import os
import re
import stat
import sys
from dataclasses import dataclass
from importlib import import_module
from pathlib import Path
from typing import Dict, List, Optional

# Local import — the manifest loader lives next to us.
sys.path.insert(0, str(Path(__file__).resolve().parent))
load_manifest = import_module("snapshot_manifest_schema").load_manifest

PYPTO_DTYPE_NAMES = {
    "float32": "pypto.DT_FP32",
    "float16": "pypto.DT_FP16",
    "bfloat16": "pypto.DT_BF16",
    "int32": "pypto.DT_INT32",
    "int64": "pypto.DT_INT64",
    "bool": "pypto.DT_BOOL",
}

MARKER_OPEN = re.compile(
    r"^(\s*)# <<< SNAPSHOT:("
    r"before_nt_loop|inside_nt_loop|after_nt_loop|"
    r"SIG_IMPL|SIG_JIT|CALL_IMPL|"
    r"HOST_WRAPPER_INSPECT_ALLOC|HOST_WRAPPER_INSPECT_PASS"
    r")\s*$"
)
MARKER_CLOSE = re.compile(
    r"^(\s*)# >>> SNAPSHOT:("
    r"before_nt_loop|inside_nt_loop|after_nt_loop|"
    r"SIG_IMPL|SIG_JIT|CALL_IMPL|"
    r"HOST_WRAPPER_INSPECT_ALLOC|HOST_WRAPPER_INSPECT_PASS"
    r")\s*$"
)

# Vocabulary of probe-point markers that take intermediate-probe blocks.
PROBE_REGIONS = {"before_nt_loop", "inside_nt_loop", "after_nt_loop"}


# -----------------------------------------------------------------------------
# Impl-side code generation
# -----------------------------------------------------------------------------

def _gen_impl_probe_block(intermediate: Dict, indent: str) -> List[str]:
    """
    Generate the pypto.assemble probe lines for one intermediate at its probe
    point. The generated code writes into inspection_<name>.

    Buffer shape is [B, H, NT, *intermediate.shape] for inside_nt_loop probes,
    [B, H, *intermediate.shape] for before/after probes (no iteration axis).
    """
    name = intermediate["name"]
    shape = intermediate["shape"]
    pp = intermediate["probe_point"]
    ind = indent

    if pp == "inside_nt_loop":
        # Expected local variables in scope at the probe point: b, h, c (= NT-1-i for reverse scan, i for forward).
        # We wrap the rank-N intermediate to rank-(N+3) by prepending [1,1,1,...].
        wrap = "[1, 1, 1, " + ", ".join(str(s) for s in shape) + "]"
        offset = "[b, h, c, " + ", ".join("0" for _ in shape) + "]"
        return [
            f"{ind}# AUTO-GENERATED by snapshot_generator.py — probe for {name}",
            f"{ind}_probe_{name}_wrapped = pypto.reshape({name}, {wrap})",
            f"{ind}pypto.assemble(_probe_{name}_wrapped, {offset}, inspection_{name})",
        ]
    if pp in ("before_nt_loop", "after_nt_loop"):
        # Expected locals in scope: b, h (no iteration axis).
        wrap = "[1, 1, " + ", ".join(str(s) for s in shape) + "]"
        offset = "[b, h, " + ", ".join("0" for _ in shape) + "]"
        return [
            f"{ind}# AUTO-GENERATED by snapshot_generator.py — probe for {name}",
            f"{ind}_probe_{name}_wrapped = pypto.reshape({name}, {wrap})",
            f"{ind}pypto.assemble(_probe_{name}_wrapped, {offset}, inspection_{name})",
        ]
    raise ValueError(f"unknown probe_point {pp!r}")


def _gen_impl_kwargs(
    intermediates: List[Dict], indent: str, pass_through: bool,
) -> List[str]:
    """Generate inspection kwargs for signatures or call-through sites."""
    arguments = []
    for intermediate in intermediates:
        name = intermediate["name"]
        value = f"inspection_{name}" if pass_through else "None"
        arguments.append(f"{indent}inspection_{name}={value},")
    return arguments


def _gen_sig_jit_kwargs(intermediates: List[Dict], indent: str) -> List[str]:
    """kwargs for the JIT entry — annotated with pypto.Tensor, default None."""
    return [
        f"{indent}inspection_{entry['name']}: "
        f"pypto.Tensor([pypto.DYNAMIC, ...], "
        f"{PYPTO_DTYPE_NAMES[entry['dtype']]}) = None,"
        for entry in intermediates
    ]


def _gen_host_wrapper_alloc(intermediates: List[Dict], indent: str) -> List[str]:
    """
    Bind buffers preallocated by snapshot_bisect. The generator cannot infer a
    host wrapper's input variable names, so silently allocating on ``x.device``
    would be incorrect for operators whose first input is not named ``x``.
    """
    out: List[str] = []
    for entry in intermediates:
        name = entry["name"]
        out.extend(
            [
                f"{indent}inspection_{name} = kwargs.get('inspection_{name}')",
                f"{indent}if inspection_{name} is None:",
                f"{indent}    raise ValueError("
                f"'inspection_{name} must be preallocated by snapshot_bisect')",
            ]
        )
    return out


def _group_by_probe_point(intermediates: List[Dict]) -> Dict[str, List[Dict]]:
    grouped: Dict[str, List[Dict]] = {}
    for entry in intermediates:
        grouped.setdefault(entry["probe_point"], []).append(entry)
    return grouped


def _generated_region_lines(region_name, indent, intermediates, by_probe_point):
    if region_name in PROBE_REGIONS:
        lines = []
        for entry in by_probe_point.get(region_name, []):
            lines.extend(_gen_impl_probe_block(entry, indent))
        return lines
    if region_name == "SIG_IMPL":
        return _gen_impl_kwargs(intermediates, indent, pass_through=False)
    if region_name in ("CALL_IMPL", "HOST_WRAPPER_INSPECT_PASS"):
        return _gen_impl_kwargs(intermediates, indent, pass_through=True)
    generators = {
        "SIG_JIT": _gen_sig_jit_kwargs,
        "HOST_WRAPPER_INSPECT_ALLOC": _gen_host_wrapper_alloc,
    }
    generator = generators.get(region_name)
    return generator(intermediates, indent) if generator else []


def _splice_impl(source: str, intermediates: List[Dict]) -> str:
    """
    Inject generated code before each closing marker. Regions supported:

      - before_nt_loop / inside_nt_loop / after_nt_loop
          → insert pypto.assemble probe blocks for matching intermediates.
      - SIG_IMPL
          → insert inspection_<name>=None kwargs into the _kernel_impl signature.
      - SIG_JIT
          → insert pypto.Tensor-typed inspection kwargs into the JIT entry signature.
      - CALL_IMPL
          → insert keyword-argument pass-through from JIT entry into _kernel_impl.
      - HOST_WRAPPER_INSPECT_ALLOC
          → allocate zero buffers inside host_wrapper(), honoring any kwargs overrides.
      - HOST_WRAPPER_INSPECT_PASS
          → pass the allocated buffers into the JIT-entry call inside host_wrapper().

    Probe blocks (before/inside/after_nt_loop) are grouped by probe_point and
    inserted at the SAME indent as the closing marker (the author is responsible
    for placing the marker pair at the correct block level).
    """
    by_probe_point = _group_by_probe_point(intermediates)
    out: List[str] = []
    inside_region: Optional[str] = None
    region_indent = ""
    for line in source.splitlines():
        m_open = MARKER_OPEN.match(line)
        m_close = MARKER_CLOSE.match(line)
        if m_open:
            inside_region = m_open.group(2)
            region_indent = m_open.group(1)
            out.append(line)
            continue
        if m_close and inside_region == m_close.group(2):
            out.extend(
                _generated_region_lines(
                    inside_region,
                    region_indent,
                    intermediates,
                    by_probe_point,
                )
            )
            inside_region = None
            out.append(line)
            continue
        out.append(line)
    return "\n".join(out) + ("\n" if source.endswith("\n") else "")


REQUIRED_MARKERS = [
    "SIG_IMPL",                         # _<op>_kernel_impl signature
    "SIG_JIT",                          # <op>_kernel_npu_impl signature
    "CALL_IMPL",                        # inside the JIT entry: call to _<op>_kernel_impl
    "HOST_WRAPPER_INSPECT_ALLOC",     # inside host_wrapper(): buffer allocation
    "HOST_WRAPPER_INSPECT_PASS",      # inside host_wrapper(): JIT call kwargs
]


def _check_required_markers(source: str, filename: str) -> None:
    """Raise ValueError if any of the required wiring markers are missing."""
    missing: List[str] = []
    for marker in REQUIRED_MARKERS:
        if (f"# <<< SNAPSHOT:{marker}" not in source
                or f"# >>> SNAPSHOT:{marker}" not in source):
            missing.append(marker)
    if missing:
        raise ValueError(
            f"missing required marker pair(s) in {filename}: {missing}. "
            "See intermediate-snapshot-automation.md for the marker contract — "
            "the kernel author must place these marker pairs at the signature, "
            "call-site, and host_wrapper locations."
        )


# -----------------------------------------------------------------------------
# Golden-side augmentation
# -----------------------------------------------------------------------------

def _gen_golden_inspect(module_id: str, intermediates: List[Dict]) -> str:
    """
    Produce the module_<k>_inspect() function body. For each intermediate, the
    golden_expression (if given in the manifest) is evaluated per chunk; the
    result is stacked along axis=2 into a [B, H, NT, *shape] tensor.

    If golden_expression is absent for an intermediate, a TODO stub is emitted
    and @pypto-op-debugger must fill it in manually.
    """
    m_num = int(module_id[1:])   # "M2" -> 2
    lines: List[str] = [
        f"def module_{m_num}_inspect(**inputs):",
        f'    """AUTO-GENERATED by snapshot_generator.py. Returns per-iteration intermediates for module {module_id}.',
        "    Output keys match the inspection_<name> buffer names on the impl side.",
        '    """',
        "    import torch",
        "    # Reuse module_<k>'s internals by running the full module, capturing intermediates via closures.",
        "    # This is a stub — @pypto-op-debugger fills in the per-iteration capture logic by looking at",
        "    # modules/<op>_module<suffix_k>_golden.py. The generator cannot AST-rewrite the golden safely.",
        "",
        "    result = {}",
    ]
    for entry in intermediates:
        name = entry["name"]
        expr = entry.get("golden_expression")
        if expr:
            lines.append(f"    # {name}: user-provided expression")
            lines.append(f"    result['{name}'] = {expr}")
        else:
            lines.append(f"    # TODO[@pypto-op-debugger]: fill in the per-iteration computation for {name}.")
            lines.append(f"    #   Expected shape: [B, H, NT, {', '.join(str(s) for s in entry['shape'])}]")
            lines.append(f"    #   dtype:          {entry['dtype']}")
            lines.append(f"    result['{name}'] = None")
    lines.append("    return result")
    lines.append("")
    return "\n".join(lines)


# -----------------------------------------------------------------------------
# Bisect shell script
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class BisectScriptSpec:
    op: str
    module: str
    case: str
    modes: List[str]
    manifest_path: str
    device: str = "9"


def _gen_bisect_sh(spec: BisectScriptSpec) -> str:
    modes_csv = ",".join(spec.modes)
    return f"""#!/usr/bin/env bash
# AUTO-GENERATED by snapshot_generator.py.
# Runs snapshot_bisect.py for {spec.op} {spec.module} on case {spec.case} across modes: {modes_csv}.

set -euo pipefail
cd "$(dirname "$0")/../../.."    # -> repo root from custom/<op>/_debug/

MANIFEST="{spec.manifest_path}"
DEVICE="${{TILE_FWK_DEVICE_ID:-{spec.device}}}"

python .opencode/skills/pypto-op-verify/scripts/snapshot_bisect.py \\
    --manifest "$MANIFEST" \\
    --modes {modes_csv} \\
    --device "$DEVICE"
"""


# -----------------------------------------------------------------------------
# Top-level driver
# -----------------------------------------------------------------------------

def _module_suffix(module):
    module_number = int(module[1:])
    return "".join(str(index) for index in range(1, module_number + 1))


def _resolve_generation_paths(manifest_path, op, module):
    manifest_file = Path(manifest_path).resolve()
    debug_dir = manifest_file.parent
    op_dir = debug_dir.parent
    if debug_dir.name != "_debug" or op_dir.name != op:
        raise ValueError(
            "snapshot manifest must live at custom/<op>/_debug/"
            "snapshot_manifest.yaml"
        )
    if op_dir.parent.name != "custom":
        raise ValueError("snapshot operator directory must be under custom/")
    repo_root = op_dir.parents[1]
    module_dir = op_dir / "modules"
    suffix = _module_suffix(module)
    source_impl = module_dir / f"{op}_module{suffix}_impl.py"
    source_golden = module_dir / f"{op}_module{suffix}_golden.py"
    if module == "M1" and not source_impl.exists() and not source_golden.exists():
        source_impl = op_dir / f"{op}_impl.py"
        source_golden = op_dir / f"{op}_golden.py"
    missing = [path for path in (source_impl, source_golden) if not path.exists()]
    if missing:
        expected = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(
            f"missing staged artifact(s) for {module} (suffix {suffix}): {expected}"
        )
    return repo_root, debug_dir, source_impl, source_golden


def _validate_probe_markers(source, source_name, intermediates):
    needed_probe_points = {entry["probe_point"] for entry in intermediates}
    for probe_point in needed_probe_points:
        opening = f"# <<< SNAPSHOT:{probe_point}"
        closing = f"# >>> SNAPSHOT:{probe_point}"
        if opening not in source or closing not in source:
            raise ValueError(
                f"marker pair {opening} / {closing} not found in {source_name}. "
                "Add the marker pair around the probe-point region before generating snapshots. "
                "See intermediate-snapshot-automation.md for the marker contract."
            )
    _check_required_markers(source, source_name)


def _retag_snapshot_impl(source, op, module):
    suffix = _module_suffix(module)
    replacements = (
        (f"{op}_module{suffix}_kernel_npu", f"{op}_{module}_snapshot_kernel_npu"),
        (f"{op}_module{suffix}_kernel", f"{op}_{module}_snapshot_kernel"),
        (f"{op}_kernel_npu_impl", f"{op}_{module}_snapshot_kernel_npu_impl"),
        (f"{op}_kernel_npu", f"{op}_{module}_snapshot_kernel_npu"),
        (f"{op}_module{suffix}_wrapper", "host_wrapper"),
    )
    for original, replacement in replacements:
        source = source.replace(original, replacement)
    if module == "M1":
        source = source.replace(f"{op}_wrapper", "host_wrapper")
    return source


def _augment_golden(source, module, intermediates):
    module_number = int(module[1:])
    if f"def module_{module_number}_inspect" not in source:
        return source + "\n\n" + _gen_golden_inspect(module, intermediates)
    return (
        source
        + f"\n\n# NOTE[snapshot_generator]: module_{module_number}_inspect already exists; "
          "generator skipped its scaffold. If the manifest adds NEW intermediates, "
          "extend the existing function by hand.\n"
    )


def _write_artifacts(paths, contents):
    paths["impl"].write_text(contents["impl"], encoding="utf-8")
    paths["golden"].write_text(contents["golden"], encoding="utf-8")
    paths["sh"].write_text(contents["sh"], encoding="utf-8")
    executable = stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    os.chmod(paths["sh"], os.stat(paths["sh"]).st_mode | executable)


def generate(manifest_path: str | Path, *, dry_run: bool = False) -> Dict[str, Path]:
    """
    Generate the three snapshot artifacts. Returns a dict of
    {artifact_name: output_path}. Raises FileNotFoundError if the source
    module file is missing; raises ValueError if markers are absent.
    """
    manifest = load_manifest(manifest_path)
    op, module = manifest["op"], manifest["module"]
    repo_root, debug_dir, source_impl, source_golden = _resolve_generation_paths(
        manifest_path, op, module
    )
    impl_source = source_impl.read_text(encoding="utf-8")
    golden_source = source_golden.read_text(encoding="utf-8")
    _validate_probe_markers(impl_source, source_impl.name, manifest["intermediates"])
    impl_with_probes = _retag_snapshot_impl(
        _splice_impl(impl_source, manifest["intermediates"]), op, module
    )
    manifest_file = Path(manifest_path).resolve()
    manifest_relative = manifest_file.relative_to(repo_root)
    paths = {
        "impl": debug_dir / f"{op}_{module}_snapshot.py",
        "golden": debug_dir / f"{op}_golden_modular_snapshot.py",
        "sh": debug_dir / "run_snapshot_bisect.sh",
    }
    contents = {
        "impl": impl_with_probes,
        "golden": _augment_golden(golden_source, module, manifest["intermediates"]),
        "sh": _gen_bisect_sh(BisectScriptSpec(
            op, module, manifest["case"], manifest["modes"], str(manifest_relative)
        )),
    }
    if dry_run:
        logging.info("DRY RUN — would write:")
        for path in paths.values():
            logging.info("  %s", path)
        return paths
    _write_artifacts(paths, contents)
    return paths


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------

def _main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    ap = argparse.ArgumentParser(description="Generate snapshot bisection artifacts from a manifest.")
    ap.add_argument("manifest", help="path to custom/<op>/_debug/snapshot_manifest.yaml")
    ap.add_argument("--dry-run", action="store_true", help="do not write files; just print what would be generated")
    args = ap.parse_args()
    paths = generate(args.manifest, dry_run=args.dry_run)
    logging.info("[OK] generated:")
    for k, p in paths.items():
        logging.info("  %-7s -> %s", k, p)
    if not args.dry_run:
        logging.info("\nNext step:")
        logging.info("  bash %s", paths["sh"])
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
