# Copyright (c) 2025-2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
"""Carry specialized IEEE scalars through the generated Pro runtime ABI."""
import ast

from .common import ContractError


def materialize_nonfinite_scalars(artifacts):
    """The pinned printer spells folded IEEE values as bare inf/nan names.

    Passing these as typed launch scalars avoids both undefined Python names and
    compiler-specific non-finite literal spellings. No arithmetic is changed.
    """
    filename = artifacts.metadata["entry"]
    source = artifacts.files[filename].decode()
    tree = ast.parse(source)
    kernel = next(node for node in tree.body if isinstance(node, ast.FunctionDef)
                  and node.name == artifacts.metadata["kernel"])
    needed = {node.id for node in ast.walk(kernel)
              if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load) and node.id in {"inf", "nan"}}
    if not needed:
        return
    defined = {node.id for node in ast.walk(tree) if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store)}
    defined.update(node.arg for node in ast.walk(tree) if isinstance(node, ast.arg))
    if needed & defined:
        raise ContractError("non-finite scalar spelling conflicts with a declared kernel name")
    renamed = {name: f"_scriptor_ieee_{name}" for name in needed}
    if set(renamed.values()) & defined:
        raise ContractError("reserved standalone IEEE scalar parameter name")

    class Replace(ast.NodeTransformer):
        def visit_Name(self, node):
            if isinstance(node.ctx, ast.Load) and node.id in renamed:
                return ast.copy_location(ast.Name(id=renamed[node.id], ctx=ast.Load()), node)
            return node

    Replace().visit(kernel)
    constants = artifacts.metadata["pypto"].setdefault("const_scalars", [])
    for name in sorted(needed):
        kernel.args.args.append(ast.arg(arg=renamed[name], annotation=ast.parse("pl.DT_FP32", mode="eval").body))
        constants.append({"name": renamed[name], "dtype": "f32", "value": float(name)})
    ast.fix_missing_locations(tree)
    artifacts.files[filename] = ("# Generated by Scriptor: IEEE values are typed runtime scalars.\n" + ast.unparse(tree) + "\n").encode()
